title: "Rasika Edirisinghe"
theme: jekyll-theme-cayman
description: "AI Researcher | NLP | Machine Learning | Deep Learning | Applied Data Visualization"
show_downloads: false

# Navigation Bar
header_pages:
  - index.md
  - current_status.md
  - industry_jobs.md
  - education.md
  - publications.md
