title: "Rasika Edirisinghe"
theme: jekyll-theme-cayman
description: "Marie Curie Early Career Researcher"
show_downloads: false

# Navigation Bar
header_pages:
  - index.md
  - current_status.md
  - academic_experience.md
  - industry_experience.md
  - education.md
  - publications.md
